### ISSUE TITLE
Found a good course for those who want to study for CCNA or fundamentals of computer networking.

### ISSUE THREAD

**Issue by KartikC137** [theredditbandit/awesome-cybersec#8]
youtube - Jeremy's It lab (Free CCNA 200-301 | Complete Course 2023) 
Link to playlist - https://youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&si=05XUVXRctTpB1fph

I am currently studying computer networking from scratch and I found this course to be very comprehensive and clear. This course is also suitable for those who don't need CCNA certification, and just want to study Computer Networking. 

Link to syllabus - https://learningnetwork.cisco.com/s/ccna-exam-topics

What is includes in the course resources (everything is free): 

1. Lab files after each lesson for practical learning (cisco packettracer tool for labs). 
2. Flashcards (Anki app), for regular revision. 

Found your repo randomly, just wanted to share this here :)

**Comment by theredditbandit** [comment]
could you raise a PR for this please

**Comment by KartikC137** [comment]
raised a PR
